### ISSUE TITLE
Livery File not found

### ISSUE THREAD

**Issue by tt3122** [RagingLightning/TSW2-Livery-Manager#1]
hello, my livery manager isnt working,
If I choose the path, shown in the install guide \documents\mygames\trainsimworld2, it says the livery file is not found.
What do i do wrong?

**Comment by RagingLightning** [comment]
quickly check, whether there is a file "Saved\SaveGames\UGCLiveries_0.sav" in that folder

**Comment by tt3122** [comment]
no. this file is not there. I installed TSW2 on my 2nd harddrive. But its not there. I have there files, where is my dtg-acc-name in it.
What im doing wrong

**Comment by RagingLightning** [comment]
try creating a livery in-game, no need to put anything in it, maybe the file isn't created, until the first livery is created

**Comment by tt3122** [comment]
another information, I searched through windows explorer search on both of my hdds. its not there. ill do this what you said.

**Comment by tt3122** [comment]
It worked. With creating a new livery, the file showed up :)
