### ISSUE TITLE
Unable to change maximum game liveries from 30

### ISSUE THREAD

**Issue by WaveyDavey13** [RagingLightning/TSW2-Livery-Manager#13]
I have tried adding the command line options of -maxGameLiveries255 and -maxGameLiveries=255 but the maximum stays set at 30.

**Comment by m-melis** [comment]
It should be `-maxGameLiveries 255`, with space between.

**Comment by WaveyDavey13** [comment]
Thanks. That has worked.

**Comment by AnD3r2710** [comment]
Where do you have to insert the command???

**Comment by RagingLightning** [comment]
@MrCreeper2710 Check out the Wiki Tab, I added Information to the corresponding page, if you still think, it is not detailed enough, feel free to open another issue
