### ISSUE TITLE
Unable to locate file!

### ISSUE THREAD

**Issue by dyingwavess** [RagingLightning/TSW2-Livery-Manager#14]
Hi, I’ve just installed your livery manager 3.0 but when I attempt to add the game deposit folder it tells me it cannot locate this. It could possibly be me but any help is appreciated :)

**Comment by m-melis** [comment]
Try to create a dummy livery in-game so that the `UGCLiveries_0.sav` file gets created in `C:\Users\YOURUSER\Documents\My Games\TrainSimWorld2\Saved\SaveGames`.

**Comment by RagingLightning** [comment]
@dyingwavess I assume, it works now, if not, please tell me
