### ISSUE TITLE
Not Letting Me Do Anything

### ISSUE THREAD

**Issue by ChewieTheHusky** [RagingLightning/TSW2-Livery-Manager#16]
The program is not letting me import/export skins, I am using onedrive could this be the case? I can't click any button also not showing up the livery slots

**Comment by RagingLightning** [comment]
Take a look at the [Getting Started](https://github.com/RagingLightning/TSW2-Livery-Manager/wiki/Getting-Started) section in the wiki, if issues persist, please comment
