### ISSUE TITLE
Can't click anything

### ISSUE THREAD

**Issue by Lukieiscool** [RagingLightning/TSW2-Livery-Manager#19]
https://gyazo.com/e29a5b1e0a1f1815bd137e66ed4af6b4

I am not able to click anything (discord is Luk#6322)

**Comment by RagingLightning** [comment]
First make sure you have selected the right folder as described on the wiki

Second, could you start the tool with `-debug` and post the resulting debug log file somewhere?

**Comment by Lukieiscool** [comment]
> First make sure you have selected the right folder as described on the wiki
> 
> Second, could you start the tool with `-debug` and post the resulting debug log file somewhere?

What do you mean with `start with -debug`

**Comment by Lukieiscool** [comment]
https://sourceb.in/Dgq8PveHmB here is the debug log

**Comment by Lukieiscool** [comment]
Fixed it, thanks for the help tho :D
