### ISSUE TITLE
Pre-fill Game folder

### ISSUE THREAD

**Issue by AlexMedia** [RagingLightning/TSW2-Livery-Manager#2]
It could be useful to pre-fill the game folder with the default location, so new users have one less thing to do. You can get the location of the user's My Documents folder using this snippet of code:

```c#
var myDocumentsFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
```

**Comment by RagingLightning** [comment]
Great Idea, addad for version 0.0.3
