### ISSUE TITLE
Can't find the location

### ISSUE THREAD

**Issue by albertosaurio65** [RagingLightning/TSW2-Livery-Manager#21]
Hello, I just bought the game in epic games, and when selecting the game path it says that it does not detect that it is the game folder

![image](https://user-images.githubusercontent.com/70109413/127534014-58eb5045-60ce-4212-9b18-e7358f77b1d4.png)

**Comment by Antotimi** [comment]
I have the exact same issue

**Comment by albertosaurio65** [comment]
i have fixed it, in epic games the folder is located here Documents\My Games\TrainSimWorld2EGS

**Comment by Antotimi** [comment]
Thanks

**Comment by RagingLightning** [comment]
I'll look into whether I can deal with Epic's different location so that it auto-detects from now on

**Comment by RagingLightning** [comment]
Fixed with 0.4
