### ISSUE TITLE
does not work with epic games version

### ISSUE THREAD

**Issue by Felzow47** [RagingLightning/TSW2-Livery-Manager#22]
![image](https://user-images.githubusercontent.com/49567056/127758746-c6bbf12a-7726-4514-8491-363fc7f01ba3.png)
![image](https://user-images.githubusercontent.com/49567056/127758755-aa0132d4-3743-40b6-b4b2-0a76b5767a02.png)
![image](https://user-images.githubusercontent.com/49567056/127758776-3e974481-b6a4-4f8e-93a4-4b1adf7cde01.png)
![image](https://user-images.githubusercontent.com/49567056/127758784-3acac084-9a54-4e75-ab93-b61918ebc527.png)
i tried with lots of places but doesn't work

**Comment by m-melis** [comment]
Create at least a livery in-game and try again.

**Comment by RagingLightning** [comment]
The correct path for Epic Games is the TrainSimWorld2EGS folder, but you need to first create a livery
