### ISSUE TITLE
Requires .NET Core but still doesn't work.

### ISSUE THREAD

**Issue by Frowny13** [RagingLightning/TSW2-Livery-Manager#23]
Every time I try to launch the program, I get an error message that looks like this.
![Capture4](https://user-images.githubusercontent.com/89502469/130725617-8ec928f2-0ce1-451c-9234-e60d1cf6fec2.JPG)
Even after I install the .NET Core thing it still doesn't work. No idea what I'm doing wrong.

**Comment by RagingLightning** [comment]
Did you install the right Version (.NET Core 3.1 found [here](https://dotnet.microsoft.com/download/dotnet-core/3.1))?

**Comment by Frowny13** [comment]
Works now. Thanks.
