### ISSUE TITLE
Microsoft Net Core problem

### ISSUE THREAD

**Issue by xX17warstarXx** [RagingLightning/TSW2-Livery-Manager#25]
The .Net Core is not found and i downloaded it a few Seconds ago

![Bild_2021-09-10_101240](https://user-images.githubusercontent.com/56962525/132822316-eac1fd77-e967-4b5a-989a-4f021eec8e2a.png)

**Comment by RagingLightning** [comment]
Are you certain that you installed .NET Core 3.1 and not the .NET Framework?

**Comment by xX17warstarXx** [comment]
> Are you certain that you installed .NET Core 3.1 and not the .NET Framework?

I installed both, is that a problem?

**Comment by RagingLightning** [comment]
It shouldn't. Maybe try installing the 32 bit Version of .NET Core aswell since that helped another user already (even though the tool is written for 64 bit...)

**Comment by xX17warstarXx** [comment]
> It shouldn't. Maybe try installing the 32 bit Version of .NET Core aswell since that helped another user already (even though the tool is written for 64 bit...)

Okay i will

**Comment by xX17warstarXx** [comment]
Well that actually worked, so thank you
