### ISSUE TITLE
Skin export ends in Crash

### ISSUE THREAD

**Issue by CmndLasley** [RagingLightning/TSW2-Livery-Manager#26]
Hey :)
When I want to Export an Train Skin the Tool Crash without any Errors. 
It works with Skins from any other DLC Trains.
But it Crash when i try to Export my Paint for the actual new DB BR 612. I dont have used external logos etc. In this skin.

**Comment by RagingLightning** [comment]
would you mind either uploading the UGCLiveries_0.sav file somewhere or contacting me on discord about it, so I can take a look at it?

Location of the .sav file:
Steam: Documents\My Games\TrainSimWorld2\Saved\SaveGames
Epic: Documents\MyGames\TrainSimWorld2EGS\Saved\SaveGames
