### ISSUE TITLE
-maxGameLiveries command not working

### ISSUE THREAD

**Issue by AnD3r2710** [RagingLightning/TSW2-Livery-Manager#27]
Hello, i wanted to increase the number of Liveries possible from 30 to 255. However the command doesn't work and the PowerShell says it's a unknown command. How do I fix this issue?
![image](https://user-images.githubusercontent.com/79704929/150147005-601963b9-f092-4daa-9cfd-36a77aa32dc9.png)

**Comment by RagingLightning** [comment]
maxGameLiveries is an argument, so you still need to specify the program. like so:

\TSW2LM_v0.5.1> `.\TSW2LM.exe -maxGameLiveries 255`

DE:
maxGameLiveries ist ein Argument, das an das Programm weitergegeben wird, daher musst du powershell das Programm mitteilen

**Comment by AnD3r2710** [comment]
Alright, thanks for the help.
