### ISSUE TITLE
unclear documentation of command line option for more liveries

### ISSUE THREAD

**Issue by MrAbelu** [RagingLightning/TSW2-Livery-Manager#29]
*no content given*

**Comment by RagingLightning** [comment]
Where exactly are you having issues, the procedure is described [here](https://github.com/RagingLightning/TSW2-Livery-Manager/wiki/(4)-Command-Line-Options)

**Comment by MrAbelu** [comment]
So i just got into train sims and i barely got this tool to work but like where do i shift right click( i know i sound dumb)

**Comment by RagingLightning** [comment]
I just made a small [video](https://youtu.be/LZxRY02GloE), hope that helps
