### ISSUE TITLE
Not supported on Windows 11 yet? Or runtime error?

### ISSUE THREAD

**Issue by FireSpirit15** [RagingLightning/TSW2-Livery-Manager#30]
The livery manager cannot be opened on Windows 11, I installed both dotnet-runtime-3.1.0-win-x64 and dotnet-runtime-3.1.0-win-x86 and also tried to use a newer version. Always the dialogue with "To run this application, install dotnet core..." pops up.
Is there any help or is it just because I am using Windows 11 and it is probably not supported?

**Comment by RagingLightning** [comment]
Did you get it from (here)[https://dotnet.microsoft.com/en-us/download/dotnet/3.1], otherwise try both x64 and x86 unter "Desktop Runtime", but also I don't have Win11, so it might be possible that it doesn't work at all

**Comment by FireSpirit15** [comment]
Thanks, that was helpful. I downloaded both, the desktop runtime and a newer version on x64 and x86, now I'm able to run the livery manager. 👍
