### ISSUE TITLE
Not working with TSW 3 UGCLiveries_0.sav files

### ISSUE THREAD

**Issue by ghost** [RagingLightning/TSW2-Livery-Manager#31]
As the title suggests the livery manager will not read TSW 3 UGCLiveries_0.sav files. It will show an error saying that the file is corrupt. It still reads TSW 2 files fine.

**Comment by ghost** [comment]
If it loads a TSW 2 version of the file it works just fine, heck you can even put the TSW 2 one into TSW 3 save games folder and it'll work. 

But if the UGCLiveries_0.sav file is generated by TSW 3, or if you make a new livery in TSW 3, the livery manager on next open will say it's corrupt.

**Comment by RagingLightning** [comment]
Not too surprised. Given that TSW3 is basically a new game, there may be many changes between the versions. I'll try and have a look at whether I can make it work for TSW3

**Comment by WaveyDavey13** [comment]
Yep I can confirm that the program doesn't work after upgrading to TSW3. Hopefully it's not too hard a fix for you and it's back up and running soon.

**Comment by RagingLightning** [comment]
I'm working on a new, TSW3-compatible version over [here](https://github.com/RagingLightning/TSW3-LM). Note that the currently released version 0.0.1 is in an ealry stage and I'm already aware, that it doesn't always wokr correctly. Use with caution!
