### ISSUE TITLE
error on folder

### ISSUE THREAD

**Issue by enrico95a** [RagingLightning/TSW2-Livery-Manager#32]
no ugcliveries_0.sav found bug to fix

**Comment by RagingLightning** [comment]
This is the **TSW2** version of the tool, unless you are actually still looking for this version, please find the TSW3 version at https://github.com/RagingLightning/TSW3-LM/releases/latest

**Comment by Eurostarfan232** [comment]
> This is the **TSW2** version of the tool, unless you are actually still looking for this version, please find the TSW3 version at https://github.com/RagingLightning/TSW3-LM/releases/latest

i have downloaded the steam version of tsw2 and it wont let me press anything

**Comment by RagingLightning** [comment]
If you are still on TSW2, you need to select the TrainSimWorld2 folder under "Documents\My Games"

if the tool still doesn't work, I'll need some more information

**Comment by Eurostarfan232** [comment]
Thanks it worked and just out of curiosity when will the windows version for the tsw3 manager work

**Comment by RagingLightning** [comment]
see [here](https://github.com/RagingLightning/TSW3-LM/issues/1#issuecomment-1298328152)
